const $ = id => document.getElementById(id);
const state = {config:null, run:null, busy:false};
const fields = ['product_name','manufacturer','upc','ndc','lot_code'];
const labels = {exact_upc:'Exact UPC',exact_ndc_family:'Exact NDC family',exact_lot_code:'Exact lot code',manufacturer_overlap:'Manufacturer overlap',strong_product_text_overlap:'Strong product text overlap',partial_product_text_overlap:'Partial product text overlap',strength_match:'Strength agrees',strength_conflict:'Strength conflicts',no_candidate_reached_review_threshold:'No source candidate reached the review threshold'};
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
async function api(path,data){const response=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error||`Request failed (${response.status})`);return value;}
function values(){return Object.fromEntries(fields.map(name=>[name,$(name).value]));}
function load(row){fields.forEach(name=>$(name).value=row[name]||'');if(state.run){state.run=null;$('result').hidden=true;$('decision-title').textContent='Evidence changed - run again';$('decision-pill').textContent='Stale result';}}
function badge(reason){return el('span',labels[reason]||reason,'reason '+(reason==='strength_conflict'?'warn':''));}
function render(run){state.run=run;const target=run.target;const display={match:'MATCH',review_needed:'REVIEW NEEDED',no_match:'NO MATCH'}[target.classification];$('result').hidden=false;$('decision-title').textContent=`CAT-005 / ${display}`;$('decision-pill').textContent='Executed';$('decision-pill').className='pill '+target.classification;$('runline').textContent=`Python completed in ${run.elapsed_ms} ms / ${run.executed_at} / run ${run.run_id.slice(0,8)}`;$('counts').replaceChildren(...[['Catalog rows',run.summary.catalog_rows],['Matches',run.summary.match],['Review',run.summary.review_needed],['No match',run.summary.no_match]].map(([label,value])=>{const card=el('div',undefined,'count');card.append(el('b',String(value)),el('span',label));return card;}));const card=$('decision-card');card.className='decision-card '+target.classification;card.replaceChildren(el('p','CAT-005 decision','step'),el('strong',display),el('span',target.classification==='review_needed'?'Shared identifiers conflict with the declared strength. A person must verify the source candidates.':target.classification==='match'?`Matched ${target.matched_recall_number} with a decisive evidence combination.`:'No selected recall record supplied enough evidence to continue.'));const candidates=$('candidates');candidates.replaceChildren(...target.pair_evidence.map(item=>{const row=el('article',undefined,'candidate');const top=el('div',undefined,'candidate-top');top.append(el('strong',item.recall_number),el('span',`${item.score} points / ${item.decision.replace('_',' ')}`));row.append(top,el('div',undefined,'reasons'));const reasonBox=row.lastChild;item.reasons.forEach(reason=>reasonBox.append(badge(reason)));if(!item.reasons.length)reasonBox.append(el('span','No supporting evidence','reason muted'));return row;}));const prov=$('provenance');prov.replaceChildren();[['Source request',run.source.source_url],['Captured',run.source.retrieved_at],['Catalog input SHA-256',run.input_sha256],['Python engine SHA-256',run.engine_sha256]].forEach(([label,value])=>{prov.append(el('strong',label),el('span',value));});target.candidate_provenance.forEach(item=>prov.append(el('strong',`${item.recall_number} fingerprint`),el('span',item.content_fingerprint)));}
async function execute(){if(state.busy)return;state.busy=true;$('run').disabled=true;$('error').hidden=true;$('runline').textContent='Executing the Python matcher...';try{render(await api('/api/run',{catalog_row:values()}));}catch(error){$('error').textContent=error.message;$('error').hidden=false;$('runline').textContent='Run failed. No result is shown as successful.';}finally{state.busy=false;$('run').disabled=false;}}
$('catalog-form').addEventListener('submit',event=>{event.preventDefault();execute();});
$('ambiguous').addEventListener('click',()=>load(state.config.default));
$('clarified').addEventListener('click',()=>load(state.config.clarified));
function download(kind){if(!state.run)return;const body=kind==='json'?JSON.stringify(state.run,null,2):state.run.csv;const url=URL.createObjectURL(new Blob([body],{type:kind==='json'?'application/json':'text/csv'}));const link=el('a');link.href=url;link.download=`recall-match-${state.run.run_id.slice(0,8)}.${kind}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('download-json').addEventListener('click',()=>download('json'));$('download-csv').addEventListener('click',()=>download('csv'));
$('verify').addEventListener('click',async()=>{$('verify').disabled=true;$('verify-status').textContent='Running Python checks...';try{const result=await api('/api/verify',{});$('verify-status').textContent=`${result.passed?'Passed':'Failed'} / ${result.executed_at}`;$('test-panel').hidden=false;$('test-panel').open=true;$('test-output').textContent=result.output;}catch(error){$('verify-status').textContent=`Checks failed to run: ${error.message}`;}finally{$('verify').disabled=false;}});
async function initialize(){try{const [config,code]=await Promise.all([api('/api/config'),api('/api/code')]);state.config=config;load(config.default);$('code').textContent=code.excerpt;}catch(error){$('error').hidden=false;$('error').textContent=`Workbench could not load: ${error.message}`;$('run').disabled=true;}}
initialize();
