const $ = id => document.getElementById(id);
const state = {selected:'noise', cases:[], run:null, busy:false, pair:0};
const names = {noise:['01','Six update labels'],cancellation:['02','A real cancellation'],sandbox:['03','Try your own rule']};
const reasons = {NO_MATERIAL_CHANGE:'No difference in the six tracked fields. Other parts of the notice may still have changed.',MISSING_CLASSIFICATION:'The category code is not supplied in this version.',MISSING_VALUE:'The value is not supplied in this version.',MISSING_DEADLINE:'The closing date is not supplied in this version.',CLASSIFICATION_NOT_ALLOWED:'The category does not match your rules.',VALUE_BELOW_MINIMUM:'The value is below your minimum.',VALUE_ABOVE_MAXIMUM:'The value exceeds your maximum.',DEADLINE_TOO_SOON:'The closing date is earlier than your rule allows.',QUALIFICATION_RULES_PASSED:'The tracked change passes the configured category, value and date checks. This is not a guarantee of legal bid eligibility.'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function api(path,data){const response=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error||`Request failed (${response.status})`);return value;}
function clearResult(){state.run=null;$('results').hidden=true;$('state').textContent='Not run yet';$('error').hidden=true;}
function selectCase(id){state.selected=id;clearResult();const item=state.cases.find(c=>c.id===id);$('data-kind').textContent=item.kind.toUpperCase();$('case-title').textContent=item.title;$('story').textContent=item.story;$('runline').textContent='Ready. The Run button executes the Python pipeline on this saved input.';document.querySelectorAll('.case').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===id));if(id==='sandbox')$('rule-details').open=true;}
function profile(){return {minimumValue:Number($('minimum').value),maximumValue:Number($('maximum').value),allowedClassificationPrefixes:$('prefixes').value.split(',').map(s=>s.trim()).filter(Boolean),deadlineOnOrAfter:$('deadline').value+'T00:00:00Z'};}
function format(value){if(value===null||value===undefined)return 'Not supplied';if(Array.isArray(value))return value.length?value.map(v=>`${v.id}: ${v.status??'not supplied'}`).join('; '):'No work packages supplied';if(typeof value==='number')return value.toLocaleString('en-GB');return String(value);}
function pairView(index){state.pair=index;const run=state.run,row=run.comparisons[index];if(!row)return;$('before-id').textContent=row.previous_release_id;$('after-id').textContent=row.current_release_id;$('fields').replaceChildren(...row.fields.map(f=>{const tr=el('tr',undefined,f.changed?'changed':'unchanged');[f.label,format(f.before),format(f.after),f.changed?'Changed':'Same'].forEach(v=>tr.append(el('td',v)));return tr;}));document.querySelectorAll('.timeline button').forEach((b,i)=>b.setAttribute('aria-pressed',i===index));$('source-tag').textContent='Source label: '+row.source_tags.join(', ');$('routes').replaceChildren(...[['accepted','Act'],['rejected','Ignore'],['review-needed','Review']].map(([key,label])=>{const active=row.decision===key;return el('div',label+(active?' ← this comparison':''),'route '+(key==='review-needed'?'review ':'')+(active?'active':''));}));$('explanation').textContent=row.reason_codes.map(r=>reasons[r]||r).join(' ');const p=$('provenance');p.replaceChildren();[['Government process',row.ocid],['Captured from source',run.captured_at],['This run executed',run.executed_at],['Fresh run ID',run.run_id],['Original release fingerprint',row.provenance.content_fingerprint],['Sanitized input file SHA-256',run.input_sha256],['Python module SHA-256',run.engine_sha256]].forEach(([label,value])=>{p.append(el('strong',label),el('span',value));});if(run.source_url.startsWith('https://')){p.append(el('strong','Official source'));const a=el('a',run.source_url);a.href=run.source_url;a.target='_blank';a.rel='noopener';p.append(a);}$('input-link').href='/api/input?case='+run.case_id;}
function renderRun(run){state.run=run;const s=run.result.summary;$('results').hidden=false;$('state').textContent='Executed on server';$('runline').textContent=`Python completed · ${run.elapsed_ms} ms · ${run.executed_at} · Run ${run.run_id.slice(0,8)}`;$('counts').replaceChildren(...[[s.input_releases,'notice versions'],[s.comparisons,'pairs compared'],[s.material_change_comparisons,'pairs with tracked changes'],[s.accepted+s.review_needed,'act or review decisions']].map(([v,label])=>{const card=el('div',undefined,'count');card.append(el('b',String(v)),el('span',label));return card;}));const insight=$('insight');insight.replaceChildren();let headline,body;if(run.case_id==='noise'){headline='The label would have over-alerted. The field comparison did not.';body=`${s.update_tagged_comparisons} update-tagged pairs, but ${s.material_change_comparisons} changes in the tracked fields. Check any pair below for yourself.`;}else if(run.case_id==='cancellation'){headline='Missing data is not the same as “nothing happened.”';body='The source calls this a cancellation. Five tracked fields differ, including absent values. The system keeps it visible in Review instead of filling in the blanks.';}else{headline=s.accepted?'The changed opportunity fits these rules.':'The changed opportunity does not fit these rules.';body='Synthetic scenario: value 400,000 GBP. Set maximum value to 300,000 or 500,000 and rerun. The input stays the same; the server recalculates the decision.';}insight.append(el('strong',headline),el('span',body));$('timeline').replaceChildren(...run.comparisons.map((row,i)=>{const b=el('button',`${i+1} · ${row.previous_release_id} → ${row.current_release_id}`);b.type='button';b.addEventListener('click',()=>pairView(i));return b;}));pairView(0);}
async function execute(){if(state.busy)return;state.busy=true;clearResult();$('run').disabled=true;document.querySelectorAll('.case').forEach(b=>b.disabled=true);$('runline').textContent='Sending the selected input and rules to the Python server…';try{renderRun(await api('/api/run',{case_id:state.selected,profile:profile()}));}catch(error){$('error').textContent=error.message;$('error').hidden=false;$('runline').textContent='Run failed. No result is being presented as successful.';}finally{state.busy=false;$('run').disabled=false;document.querySelectorAll('.case').forEach(b=>b.disabled=false);}}
$('rules').addEventListener('submit',event=>{event.preventDefault();execute();});$('rules').addEventListener('input',()=>{if(state.run){clearResult();$('runline').textContent='Rules changed. Run again to calculate a new result.';}});
function download(kind){if(!state.run)return;const body=kind==='json'?JSON.stringify(state.run,null,2):state.run.csv;const url=URL.createObjectURL(new Blob([body],{type:kind==='json'?'application/json':'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download=`proof-${state.run.case_id}-${state.run.run_id.slice(0,8)}.${kind}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('download-json').addEventListener('click',()=>download('json'));$('download-csv').addEventListener('click',()=>download('csv'));
$('verify').addEventListener('click',async()=>{$('verify').disabled=true;$('verify-status').textContent='Executing the automated Python checks…';try{const result=await api('/api/verify',{});$('verify-status').textContent=(result.passed?'Passed':'Failed')+' · '+result.executed_at;$('test-panel').hidden=false;$('test-output').textContent=result.output;$('test-panel').open=true;}catch(error){$('verify-status').textContent='Checks could not complete: '+error.message;}finally{$('verify').disabled=false;}});
async function initialize(){try{const [data,code]=await Promise.all([api('/api/cases'),api('/api/code')]);state.cases=data.cases;const p=data.profile;$('minimum').value=p.minimumValue;$('maximum').value=p.maximumValue;$('prefixes').value=p.allowedClassificationPrefixes.join(', ');$('deadline').value=p.deadlineOnOrAfter.slice(0,10);$('cases').replaceChildren(...data.cases.map(c=>{const b=el('button',undefined,'case');b.dataset.id=c.id;const text=el('div');text.append(el('strong',names[c.id][1]),el('small',c.kind));b.append(el('span',names[c.id][0],'number'),text);b.addEventListener('click',()=>selectCase(c.id));return b;}));$('diff-code').textContent=code.diff;$('qual-code').textContent=code.qualification;selectCase('noise');}catch(error){$('error').hidden=false;$('error').textContent='Cannot load the Proof Lab: '+error.message;$('run').disabled=true;}}
initialize();
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tool={name:'run_contract_comparison',title:'Run saved contract example',description:'Execute the real Python comparison using a selected saved example and the business rules currently visible. Updates the visible results. Does not collect new government data.',inputSchema:{type:'object',properties:{case_id:{type:'string',enum:['noise','cancellation','sandbox']}},required:['case_id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||Object.keys(input).some(k=>k!=='case_id')||!state.cases.some(c=>c.id===input.case_id))throw Error('Select a known loaded case.');if(state.busy)throw Error('A run is already in progress.');selectCase(input.case_id);await execute();if(!state.run)throw Error('Comparison failed; see visible error.');return {run_id:state.run.run_id,summary:state.run.result.summary};}};
 Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
